# since we don't need sudo, travis recommend xenial
dist: xenial

language: node_js

# we don't need previous commits, so don't need default depth of 50
git:
  depth: 1

# have to enable branch build to trigger on git tag but
# we don't want the same job to run twice on pull request
branches:
  only:
    - master
    - dev
    - /^v.*$/ # Ensure to build release tags of format v1.0.0-1

stages:
  - name: test
    if: tag IS NOT present
  - name: publish
    if: tag IS present # https://docs.travis-ci.com/user/conditions-v1

install:
  - npm install

script:
  - printenv | sort
jobs:
  include:
    - stage: test
      name: "Unit Tests on Node 8"
      node_js: "8"
      script:
        - npm run test:ci
      after_success:
        - pwd
        - ls -lt coverage/
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - name: "Unit Tests on Node 10"
      node_js: "10"

    - stage: publish
      name: "NPM release for dev" # rename before merge to master
      node_js: "8"
      before_deploy: 
        - npm run build
      deploy:
        - provider: npm
          email: $NPM_EMAIL_ACCOUNT
          api_key: $NPM_TOKEN
          skip_cleanup: true
          tag: beta   # tag all npm publish from dev branch with "beta" TODO: remove before merge to master
          on: # https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on
            tags: true
            repo: serverless/serverless-azure-functions
